%YAML:1.0

# Project
project_name: "lvi_sam"

#common parameters
imu_topic: "/ms/imu/data"
image_topic: "/forwardLeft/image_raw"
point_cloud_topic: "/ouster/points"

# Lidar Params
use_lidar: 1                     # whether use depth info from lidar or not
lidar_skip: 3                    # skip this amount of scans
align_camera_lidar_estimation: 1 # align camera and lidar estimation for visualization

# camera model
model_type: KANNALA_BRANDT
camera_name: camera

# Mono camera config
image_width: 2048
image_height: 1536

projection_parameters:
   mu: 1057.8085759554679
   mv: 1057.8344071878955
   u0: 1031.0394456453769
   uv: 727.7604933179784
   k2: -0.03999018098363963
   k3: 0.0035531756082936186
   k4: -0.0006681279528559426
   k5: -0.0009677749839773924
#fisheye_mask: "/config/fisheye_mask_720x540.jpg"

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.001093618          # accelerometer measurement noise standard deviation. 
gyr_n: 0.00060369579         # gyroscope measurement noise standard deviation.     
acc_w: 4.584471e-05        # accelerometer bias random work noise standard deviation.  
gyr_w: 3.22094e-05       # gyroscope bias random work noise standard deviation.
g_norm: 9.81007     # gravity magnitude


# Extrinsic parameter between IMU and Camera. Tic
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.0521232345, -0.0073054379,  0.9986139389,
          -0.9986040017, -0.0089493528,  0.0520572461, 
           0.0085566474, -0.9999332676, -0.0077617087]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.1219040939, 0.0366053924, -0.0562970105]


#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04   # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0  # keyframe selection threshold (pixel)

#unsynchronization parameters
estimate_td: 0           # online estimate time offset between camera and imu
td: 0                    # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0       # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0    # unit: s. rolling shutter read out time per frame (from data sheet). 

#loop closure parameters
loop_closure: 1                    # start loop closure
skip_time: 0.0
skip_dist: 0.0
debug_image: 0                      # save raw image in loop detector for visualization prupose; you can close this function by setting 0 
match_image_scale: 0.5
vocabulary_file: "/config/brief_k10L6.bin"
brief_pattern_file: "/config/brief_pattern.yml"